os: Visual Studio 2014
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

configuration: Release
branches:
  only:
    - master

before_build:
  - nuget restore FluentBootstrapPolicy.sln

build:
  project: FluentBootstrapPolicy.sln       
  verbosity: minimal

test:
  assemblies:
    - '**\*.Tests.dll'